//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaRoomWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public int Id { get; set; }
        public string tipo_habitacion { get; set; }
        public string servicios { get; set; }
        public long precio_hr { get; set; }
        public long precio_dia { get; set; }
        public int HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
