//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaRoomWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Habitaciones = new HashSet<Habitacion>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombre_hotel { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombre_director { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string direccion_postal { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string imagen_hotel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitacion> Habitaciones { get; set; }
    }
}
