//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaRoomWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public double precio_hr { get; set; }
        public double precio_dia { get; set; }
        public double precio_total { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
